export const LOGIN = 'dDAdada111'
export const EMAIL = 'ds8054296@gmail.com'
export const PASSWORD = 'Gameplay92121'
export const PERSONAL_TOKEN = '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'
export const REPO ='Test'